Update to latest ct firmware. Add wildcard 802.11r fast transition support. Move openvswitch config database to /tmp. Fix DFS with latest ct firmware (now you can change to a DFS channel)

diff --git a/patches/packages/0173-hostapd-procd-respawn.patch b/patches/packages/0173-hostapd-procd-respawn.patch
--- a/patches/packages/0173-hostapd-procd-respawn.patch
+++ b/patches/packages/0173-hostapd-procd-respawn.patch
@@ -9,13 +9,14 @@
  	if [ "$?" = "0" ] ; then
  		echo "Interface $ifname is up prematurely! Taking it back down..."
  		ip link set "$ifname" down
-@@ -608,7 +608,15 @@ mac80211_setup_vif() {
+@@ -608,7 +608,16 @@ mac80211_setup_vif() {
  	json_get_vars mode
  	json_get_var vif_txpower txpower
  
 -	ip link set dev "$ifname" up || {
 +	# hostapd needs some extra time if it's doing auto channel or DFS
-+	retries=45
++	retries=60
++	logger "Waiting up to 60 seconds for radio to acquire channel..."
 +	while [ "$retries" -ge 0 ] ; do
 +		ip link set dev "$ifname" up > /dev/null 2>&1 && break
 +		sleep 1
@@ -26,7 +27,7 @@
  		wireless_setup_vif_failed IFUP_ERROR
  		json_select ..
  		return
-@@ -674,7 +682,7 @@ mac80211_interface_cleanup() {
+@@ -674,7 +683,7 @@ mac80211_interface_cleanup() {
  
  	for wdev in $(list_phy_interfaces "$phy"); do
  		ip link set dev "$wdev" down 2>/dev/null
@@ -35,7 +36,17 @@
  	done
  }
  
-@@ -747,15 +755,15 @@ drv_mac80211_setup() {
+@@ -693,6 +702,9 @@ drv_mac80211_setup() {
+ 	json_get_values basic_rate_list basic_rate
+ 	json_select ..
+ 
++	# Restart the watchdog to avoid false positive triggers during reload
++	/etc/init.d/wifi-watchdog restart || true
++
+ 	find_phy || {
+ 		echo "Could not find PHY for device '$1'"
+ 		wireless_set_retry 0
+@@ -747,15 +759,15 @@ drv_mac80211_setup() {
  	for_each_interface "ap" mac80211_prepare_vif
  
  	[ -n "$hostapd_ctrl" ] && {
@@ -60,7 +71,7 @@
  	}
  
  	for_each_interface "ap sta adhoc mesh monitor" mac80211_setup_vif
-@@ -779,6 +787,8 @@ drv_mac80211_teardown() {
+@@ -779,6 +791,8 @@ drv_mac80211_teardown() {
  	json_get_vars phy
  	json_select ..
  
