Add SMS delete support and SMS pattern matching with man3g. Use pattern matching in 3g_connmgr to check for the reboot code, delete the sms and watchdog reboot.

diff --git a/imagestream/package/netifd-qmi/files/bin/man3g b/imagestream/package/netifd-qmi/files/bin/man3g
--- a/imagestream/package/netifd-qmi/files/bin/man3g
+++ b/imagestream/package/netifd-qmi/files/bin/man3g
@@ -174,56 +174,9 @@ EOM
 	fi	
 }
 
-uqmi_display_sms() {
-	id=$1
-	if [ "$machine" = "0" ] ; then
-		echo -n "Message $((id+1)) "
-		uqmi -d $CDCDEV --get-message $id 2>/dev/null
-	else
-		SMS_TMP="/tmp/man3g_sms.$$"
-		uqmi -d $CDCDEV --get-message $id > $SMS_TMP 2>/dev/null
-		# ID, Status, SMSC, Sender, Date, Message
-		echo "$((id+1))"
-		echo "0"
-		while read line
-		do
-			read line
-			echo "$line" | grep '"smsc":' | awk '{print $2}' | cut -d ',' -f 1
-			read line
-			echo "$line" | grep '"sender":' | awk '{print $2}' | cut -d ',' -f 1
-			read line
-			ts=`echo "$line" | grep '"timestamp":' | cut -d ',' -f 1 | awk '{print $2","$3}'`
-			tzo=`date +%z`
-			# Ok this needs explaining. The output should look like: "2010-12-13,18:43:49.0,-06:00"
-			# The ts string looks like: "2010-12-13,18:43:49" so I use a neat bash substring trick to
-			# print all but the last character of ts (substring start at 0 through length -1) and
-			# also split the timezone from -0600 to the format -06:00.
-			echo "${ts:0:(-1)}.0,${tzo:0:3}:${tzo:3}\""
-			read -r line
-			message=`echo -E "$line" | grep '"text":' | cut -d ':' -f 2- | cut -b 2-`
-			echo ${#message}
-			echo -E $message
-			break
-		done < ${SMS_TMP}
-		rm -f ${SMS_TMP}
-	fi
-}
-
-uqmi_display_sms_all() {
-	
-	MSG_LIST=`uqmi -d $CDCDEV --list-messages | sed 's/,//g'`
-	for idx in $MSG_LIST ; do
-		case $idx in
-			''|*[!0-9]*) ;;
-			*)
-				display_sms $idx
-			;;
-		esac
-	done
-}
-
 do_parse_sms() {
 	want_id=$1
+	match="$2"
 	SMS_TMP="/tmp/man3g_sms.$$"
 	gcom -d ${MODEMDEV} -s /etc/gcom/man3g_readallsms.gcom > $SMS_TMP 2>/dev/null
 	while : ;
@@ -291,6 +244,7 @@ do_parse_sms() {
 		if [ "$machine" = "0" ] ; then
 			echo
 		fi
+		[ "$match" != "" ] && echo "$message" | grep "$match" > /dev/null 2>&1 && found=$((id+1))
 		if [ "${line:0:6}" != "+CMGL:" ] ; then
 			read line || break
 		fi
@@ -302,26 +256,9 @@ do_parse_sms() {
 }
 
 display_sms() {
-	id=$1
-	do_parse_sms $id
+	do_parse_sms "$1" "$2"
 }
 
-display_sms_all() {
-	do_parse_sms
-}
-
-uqmi_display_sms_all() {
-	
-	MSG_LIST=`uqmi -d $CDCDEV --list-messages | sed 's/,//g'`
-	for idx in $MSG_LIST ; do
-		case $idx in
-			''|*[!0-9]*) ;;
-			*)
-				display_sms $idx
-			;;
-		esac
-	done
-}
 send_sms() {
 	export SMS_NUMBER="$number"
 	export SMS_MESSAGE="$message"
@@ -333,6 +270,19 @@ send_sms() {
 		echo "Unable to send SMS message, error $id"
 	else
 		echo "Unable to send SMS message, unable to communicate with modem!"
+	fi
+}
+delete_sms() {
+	id=$1
+	export SMS_ID="$id"
+	out=`gcom -d ${MODEMDEV} -s /etc/gcom/man3g_deletesms.gcom`
+	RET="$?"
+	if [ "$RET" = "0" ] ; then
+		echo "SMS message $((id+1)) deleted"
+	elif [ "$RET" = "1" ] ; then
+		echo "Unable to delete SMS message, error $out"
+	else
+		echo "Unable to delete SMS message, unable to communicate with modem!"
 	fi
 }
 
@@ -372,13 +322,13 @@ do_lock() {
     # verify that we got it!
     do_lock
     LOCKED=1
-    logger "Man3g: PID $$ took lock..."
+#    logger "Man3g: PID $$ took lock..."
 }
 
 do_unlock() {
     rm -f ${LCKFILE}
     LOCKED=0
-    logger "Man3g: PID $$ released lock..."
+#    logger "Man3g: PID $$ released lock..."
 }
 
 do_exit() {
@@ -401,7 +351,9 @@ if [ "$1" = "" ] ; then
 	usage
 fi
 machine=0
-msgid=-1
+msgid=""
+match=""
+found=0
 while [ $# -gt 0 ] ; do
 	if [ "$1" = "--machine" ] ; then
 		machine=1
@@ -415,6 +367,9 @@ while [ $# -gt 0 ] ; do
 	elif [ "$1" = "--message" ] ; then
 		shift
 		message=$1
+	elif [ "$1" = "--match" ] ; then
+		shift
+		match=$1
 	else
 		cmd=$1
 	fi
@@ -425,21 +380,16 @@ case $cmd in
 	status)
 		status
 	;;
-	udisplay-sms)
-		do_lock
-		if [ $((msgid)) -ge 0 ] ; then
-			uqmi_display_sms $msgid
-		else
-			uqmi_display_sms_all
-		fi
-		do_unlock
-	;;
 	display-sms)
 		do_lock
+		display_sms "$msgid" "$match"
+		do_unlock
+		exit $found
+	;;
+	delete-sms)
+		do_lock
 		if [ $((msgid)) -ge 0 ] ; then
-			display_sms $msgid
-		else
-			display_sms_all
+			delete_sms $msgid
 		fi
 		do_unlock
 	;;
